version: '3'
services:

  mongodb:
    image: mongo:5.0.3-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks: 
      - hello-docker-net

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks: 
      - hello-docker-net

  hello-docker:
    image: ezeparziale/hello-docker:latest
    environment: 
      - NODE_ENV=DOCKER_CLIE
      - HOST=localhost
      - PORT=3000
      - DB_HOST=mongodb
      - DB_NAME=nba
      - DB_COLLECTION=players
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASS=password
    ports:
      - 3000:3000
    networks: 
      - hello-docker-net

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

networks:
  hello-docker-net:
    name: hello-docker-net