version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  hello-docker:
    image: ezeparziale/hello-docker:latest
    environment: 
      - NODE_ENV=DOCKER_CLIE
      - HOST=localhost
      - PORT=3000
      - DB_HOST=mongodb
      - DB_NAME=nba
      - DB_COLLECTION=players
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASS=password
    ports:
      - 3000:3000
volumes:
  mongo-data:
    driver: local
networks:
  hello-docker-net:
    name: hello-docker-net