name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-push-image-docker:

    runs-on: ubuntu-latest

    steps:
  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{  secrets.DOCKER_USER  }}/${{ github.event.repository.name }}:2.0, ${{  secrets.DOCKER_USER  }}/${{ github.event.repository.name }}:latest

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{  secrets.DOCKER_USER  }}/${{ github.event.repository.name }}
        short-description: ${{ github.event.repository.description }}
