name: Docker Image CI

on:
  push:
    branches: [ disable ]
  pull_request:
    branches: [ disable ]

jobs:

  build-and-push-image-docker:

    runs-on: ubuntu-latest

    steps:
  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{  secrets.DOCKER_USER  }}/${{ github.event.repository.name }}:latest
